app:
  name: "GinChat"
  version: "1.0.0"
mysql:
  dns: root:123456@tcp(127.0.0.1:3307)/ginchat1?charset=utf8mb4&parseTime=True&loc=Local
jwt:
  secret: "wGwkVzg1VzH5fTA0X/oyR0XDYymHWtiOWIvBIOAEgSw=" # 替换为您的安全密钥
  expire: 24 # token有效期(小时)
redis:
    addr: "127.0.0.1:6379"    # Redis服务器地址
    password: "123456"              # 密码（如果没有密码留空）
    db: 0                     # 数据库索引
    pool_size: 100            # 连接池大小
    min_idle_conn: 10         # 最小空闲连接数
    max_retries: 3            # 最大重试次数
    dial_timeout: 5           # 连接超时（秒）
    read_timeout: 3           # 读取超时（秒）
    write_timeout: 3          # 写入超时（秒